### ISSUE TITLE
ArgumentException - Parameter, Message parameters

### ISSUE THREAD

**Issue by IgorWolbers** [deniszykov/code-contracts-remover#1]
Converting 

    Contract.Requires<ArgumentException>(expression, message);

yields this when executing the tool with the `Convert` option:

    if (expression) {  throw new ArgumentException("parameter", "message"); }

But the [`string,string` constructor for `ArgumentException`][1] is the opposite, the correct generated line should be:

    if (expression) {  throw new ArgumentException("message", "parameter"); }

In the case where [`ArgumentNullException`][2] is used instead of [`ArgumentException`][1] it is correct as that order happens to be the inverse. *I am guessing it was 2 different developers that wrote those 2 classes a long time ago*

Thanks for your time in writing this extension/package and it is a shame Code Contracts never really took off (IMO).

[1]:https://docs.microsoft.com/en-us/dotnet/api/system.argumentexception.-ctor?view=netframework-4.8#System_ArgumentException__ctor_System_String_System_String_
[2]:https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.-ctor?view=netframework-4.8#System_ArgumentNullException__ctor_System_String_System_String_

**Comment by deniszykov** [comment]
Thanks for bug report. I will fix this soon.

It's a shame for MS that Code Contracts has not been fully integrated.

**Comment by deniszykov** [comment]
Fixed in code and in [Nuget](https://www.nuget.org/packages/CodeContractsRemover/).

**Comment by IgorWolbers** [comment]
That was fast, thank you!
